# Custom Language File for Launcher Customizer

[ejs.app]
title = "Sworld Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@FreedomOfficielOGS"
mediaDiscordURL = "https://discord.gg/JugCu63ntc"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO SWORLD"
welcomeDescription = "Oublie le launcher de base, SWORLD est fait pour toi !"
welcomeDescCTA = "Rejoind nous maintenant !"
