# Custom Language File for Launcher Customizer

[ejs.app]
title = "nipniplauncher"

[ejs.landing]
mediaGitHubURL = "https://github.com/ProjectXcraft/NipNipGame"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@FreedomOfficielOGS"
mediaDiscordURL = "https://discord.gg/VUYyCKMDZS"

[ejs.settings]
sourceGithubLink = "https://github.com/ProjectXcraft/NipNipGame"
supportLink = "https://github.com/ProjectXcraft/NipNipGame/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO NipNipGame"
welcomeDescription = "Have Fun"
welcomeDescCTA = "You are just a few clicks away from NipNip."
